#!/usr/bin/env python3
import json
from pathlib import Path
import textwrap

root = Path(__file__).resolve().parents[1]
locales_dir = root / 'examples' / 'locales'
out_file = root / 'internal' / 'simpletrans' / 'embedded_translations.go'

locale_files = sorted([p for p in locales_dir.glob('*.json') if 'backup' not in p.name])

# load and flatten similar to previous script

def flatten(d, prefix=''):
    items = {}
    if isinstance(d, dict):
        for k, v in d.items():
            new_key = f"{prefix}.{k}" if prefix else k
            if isinstance(v, dict):
                items.update(flatten(v, new_key))
            else:
                items[new_key] = v
    return items

all_locales = {}
for f in locale_files:
    try:
        data = json.loads(f.read_text())
    except Exception as e:
        print(f"Skipping {f}: {e}")
        data = {}
    fm = flatten(data)
    all_locales[f.stem] = fm

# generate Go source
out = []
out.append('// Code generated by scripts/embed_locales_to_go.py; DO NOT EDIT.')
out.append('package simpletrans')
out.append('')
out.append('var EmbeddedTranslations = map[string]map[string]string{')
for loc, kv in all_locales.items():
    out.append(f'\t"{loc}": map[string]string{'{'}')
    for k, v in sorted(kv.items()):
        # escape backquotes and quotes
        safe = v.replace('"', '\\"') if isinstance(v, str) else str(v)
        out.append(f'\t\t"{k}": "{safe}",')
    out.append('\t},')
out.append('}')

out_file.parent.mkdir(parents=True, exist_ok=True)
out_file.write_text('\n'.join(out)+"\n")
print(f"Wrote {out_file}")
